context:
  version: "0.8.0"

package:
  name: diskus
  version: ${{ version }}

source:
  url: https://github.com/sharkdp/diskus/archive/v${{ version }}.tar.gz
  sha256: 9733570d64a1eafcf96fe233fd978ec3855c77705005037ad253c49a188fdf51

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - diskus --help

about:
  license: MIT
  license_file:
    - LICENSE-MIT
    - THIRDPARTY.yml
  summary: "Minimal, fast alternative to 'du -sh'"
  homepage: https://github.com/sharkdp/diskus
  repository: https://github.com/sharkdp/diskus

extra:
  recipe-maintainers:
    - danielnachun
